#!/bin/bash
### bootstrap
source ${SHF3_HOME:-${HOME}/shf3}/lib/header
import gui
import sys

### cufu
include ${gdn}/lib

### os detection
_os=$(sys/os)
if test "${_os}" = "linux" ; then
  cufu_cuda_home="${CUDA_HOME:-/opt/cuda}"
elif test "${_os}" = "osx" ; then
  cufu_cuda_home="${CUDA_HOME:-/usr/local/cuda}"
else
  msg "OS not supported"
  exit ${_false_}
fi

### actions
actions="cudaError_enum cudaDeviceProp"

### help
function help/cufu() {
  cat << EOF

CUDA to Fortran Converter

Actions: $actions

EOF
  exit ${_false_}
}

### args
_pgi=false
while getopts hp o; do
  case "$o" in
    p) _pgi=true;;
    h|*) help/cufu;;
  esac
done

### main
_pre="header"
if ! ${_pgi} ; then
  _pre="${_pre}/isoc"
fi

import ${gbn}/${_pre}

msg "CUDA 2 FORTRAN"
gui/line
for i in ${actions} ; do
  msg "Action: ${i}"

  cufu/${_pre}/${i}
done
